### ISSUE TITLE
Telegram chat msg dont relay in minecraft chat

### ISSUE THREAD

**Issue by ghost** [glitchless/MinecraftTelegramBridge#5]
wats wrong?

**Comment by ghost** [comment]
i've privacy mode Disable with botfather

**Comment by LionZXY** [comment]
Actual yet?

**Comment by LionZXY** [comment]
Group turn on?

**Comment by ghost** [comment]
yes i use the same Bot with node .js and it does read the chat group messages
with same token

**Comment by ghost** [comment]
mmm mysteriously, when you turn off the node.js it does relay the chat.
Can not the 2 processes be at the same time?

**Comment by LionZXY** [comment]
Telegram doesn't work like that :)
